repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        exclude: ^app/tests/
        args: ["--config-file=mypy.ini"]
        additional_dependencies: [
          "fastapi",
          "sqlalchemy",
          "asyncpg",
          "types-python-jose",
          "types-passlib",
          "pydantic",
          "uuid6",
          "python-ulid",
          "bcrypt",
          "click",
          "alembic",
          "pydantic_settings"
        ]