[tool.poetry]
name = "task"
version = "0.1.0"
description = ""
authors = ["Author <author@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
uvicorn = "^0.23.2"
httpx = "^0.25.0"
fastapi = "^0.115.6"
sqlalchemy = "^2.0.37"
asyncpg = "^0.30.0"
uuid6 = "^2025.0.1"
python-ulid = "^3.1.0"
python-jose = "^3.5.0"
passlib = "^1.7.4"
bcrypt = "^5.0.0"
python-multipart = "^0.0.27"
click = "^8.3.3"
pydantic = {extras = ["email"], version = "^2.13.4"}
celery = "^5.6.3"
redis = "^7.4.0"
flower = "^2.0.1"
psycopg2-binary = "^2.9.12"
pydantic-settings = "^2.14.1"

[tool.poetry.group.dev.dependencies]
faker = "^19.10.0"
pytest = "^7.4.2"
pytest-alembic = "^0.10.7"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
pytest-env = "^1.0.1"
pytest-httpx = "^0.26.0"
pytest-mock = "^3.11.1"
pytest-mock-server = "^0.3.0"
pytest-xdist = "^3.3.1"
mypy = "^1.19.1"
pre-commit = "^4.5.1"
ruff = "^0.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py313"

include = ["*.py"]

line-length = 120

fix = true

show-fixes = true

[tool.ruff.lint]
select = [
    "E", # PEP8 ошибки
    "W", # PEP8 предупреждения
    "F", # ошибки логики
    "I", # порядок импортов
    "Q", # кавычки

    "B", # потенциальные баги
    "S", # безопасность

    "C90", # сложность кода
    "UP", # автообновление до более современных стандартов
    "RUF", # ruff правила

    "N", # PEP8 имена

    "T", # flake8-todos

    "ASYNC",

    "PERF",

    "SIM"
]

ignore = ["B008"]

fixable = ["I", "UP", "RUF", "E", "W", "F", "Q"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"app/tests/**/*.py" = ["S101", "S106", "S107"]
"app/manage.py" = ["RUF001"]