"""add cascade delete to refresh_token

Revision ID: 12d269059ac3
Revises: 3449d870c9d3
Create Date: 2026-05-25 09:27:46.654932

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12d269059ac3"
down_revision: str | Sequence[str] | None = "3449d870c9d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("refresh_token_user_id_fkey"), "refresh_token", type_="foreignkey")
    op.create_foreign_key(None, "refresh_token", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_token", type_="foreignkey")
    op.create_foreign_key(op.f("refresh_token_user_id_fkey"), "refresh_token", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
